apiVersion: apps/v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: capi-rest
    name: capi-rest
  spec:
    ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    selector:
      app: capi-rest
    type: LoadBalancer
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: capi-rest
    name: capi-rest
  spec:
    selector:
      matchLabels:
        app: capi-rest
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: capi-rest
      spec:
        containers:
        - env:
          - name: server.ssl.enabled
            value: "true"
          - name: server.ssl.key-alias
            value: capigateway
          - name: server.ssl.key-store
            value: /keys/capi.p12
          - name: server.ssl.key-store-password
            value: capigateway
          - name: server.ssl.key-store-type
            value: PKCS12
          - name: server.ssl.trust-store
            value: /keys/truststore.jks
          - name: server.ssl.trust-store-password
            value: capigateway
          - name: spring.data.mongodb.database
            value: capi
          - name: spring.data.mongodb.authentication-database
            value: admin
          - name: spring.data.mongodb.host
            value: mongo
          - name: spring.data.mongodb.password
            value: capi
          - name: spring.data.mongodb.port
            value: "27017"
          - name: spring.data.mongodb.username
            value: capi
          - name: keycloak.auth-server-url
            value: https://keycloak:8443/auth
          - name: keycloak.realm
            value: capi 
          - name: keycloak.resource
            value: rest  
          - name: keycloak.public-client
            value: "true"
          - name: keycloak.truststore
            value: /keys/truststore.jks
          - name: keycloak.truststore-password
            value: capigateway
          - name: javax.net.ssl.trustStore
            value: /keys/truststore.jks  
          - name: gateway.environment
            value: dev
          - name: gateway.cache.zookeeper.discovery
            value: "true"         
          - name: gateway.cache.zookeeper.host
            value: zookeeper:2181
          - name: gateway.cache.zookeeper.path
            value: /discovery/hazelcast
          - name: gateway.cache.zookeeper.group.key
            value: capi    
          image: surisoft/capi-gateway-rest:1.4.6
          name: capi-rest
          ports:
          - containerPort: 8080
          resources: {}
          volumeMounts:
          - name: capi-rest-certificate
            mountPath: /keys/capi.p12
            subPath: capi.p12
          - name: capi-rest-truststore
            mountPath: /keys/truststore.jks
            subPath: truststore.jks 
        restartPolicy: Always
        volumes:
        - name: capi-rest-certificate
          configMap:
            name: capi-rest-certificate
        - name: capi-rest-truststore
          configMap:
            name: capi-rest-truststore
  status: {}
kind: List
metadata: {}
