apiVersion: apps/v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: zipkin
    name: zipkin
  spec:
    ports:
    - name: "{{ .Values.service.port }}"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    selector:
      app: zipkin
    type: LoadBalancer
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: zipkin
    name: zipkin
  spec:
    selector:
      matchLabels:
        app: zipkin
    replicas: 1
    strategy: {}
    template:
      metadata:
        labels:
          app: zipkin
      spec:
        containers:
        - image: {{ .Values.image.repository }}
          name: capi-zipkin
          ports:
          - containerPort: {{ .Values.service.port }}
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}

